import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Check, Plus, Sparkles } from "lucide-react";
import { AppShell } from "./app-shell";
import { GlassCard, inputClass } from "./primitives";
import { Button } from "@/components/ui/button";
import { initialTasks, quickActions } from "@/lib/echo-data";

export function Dashboard() {
  const [tasks, setTasks] = useState(initialTasks);
  const [tab, setTab] = useState<"pending" | "completed">("pending");
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const visible = tasks.filter((t) => tab === "completed" ? t.done : !t.done);
  const add = () => { if (!name.trim()) return; setTasks([...tasks, { id: Date.now(), title: name.trim(), done: false }]); setName(""); setOpen(false); };
  return <AppShell><section className="mb-10"><div className="flex items-center gap-2 text-sm font-medium text-primary"><Sparkles className="size-4"/>Sunday, 20 September</div><h1 className="mt-3 text-4xl font-semibold md:text-6xl">Good evening, Linkesh.</h1><p className="mt-3 text-lg text-muted-foreground">Your tasks today, sir.</p></section>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><GlassCard className="min-h-96"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl bg-muted p-1"><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "pending" ? "bg-surface-strong shadow-soft" : "text-muted-foreground"}`} onClick={() => setTab("pending")}>Pending <span className="ml-1 opacity-60">{tasks.filter(t => !t.done).length}</span></button><button className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "completed" ? "bg-surface-strong shadow-soft" : "text-muted-foreground"}`} onClick={() => setTab("completed")}>Completed</button></div><Button size="sm" onClick={() => setOpen(true)}><Plus className="size-4"/>Add task</Button></div><div className="grid gap-2">{visible.map((task, i) => <button key={task.id} onClick={() => setTasks(tasks.map(t => t.id === task.id ? { ...t, done: !t.done } : t))} className="group flex items-center gap-3 rounded-xl border border-border bg-background/45 p-3 text-left transition hover:bg-accent"><span className={`grid size-6 place-items-center rounded-lg border ${task.done ? "border-primary bg-primary text-primary-foreground" : "border-input"}`}>{task.done && <Check className="size-4"/>}</span><span className="w-6 text-xs text-muted-foreground">{i + 1}.</span><span className={task.done ? "text-muted-foreground line-through" : ""}>{task.title}</span></button>)}{visible.length === 0 && <p className="py-16 text-center text-sm text-muted-foreground">Nothing here. You’re all caught up.</p>}</div></GlassCard>
    <GlassCard><p className="text-xs font-bold uppercase text-muted-foreground">Today at ECHO</p><div className="mt-5 grid gap-5"><div><strong className="text-3xl">18</strong><p className="text-sm text-muted-foreground">activities scheduled</p></div><div className="h-px bg-border"/><div><strong className="text-3xl">96.4%</strong><p className="text-sm text-muted-foreground">team attendance</p></div><div className="h-px bg-border"/><div><strong className="text-3xl">₹4.2L</strong><p className="text-sm text-muted-foreground">payments expected</p></div></div></GlassCard></div>
    <section className="mt-10"><div className="mb-5"><h2 className="text-2xl font-semibold">Quick actions</h2><p className="mt-1 text-sm text-muted-foreground">Move work forward in a few clicks.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{quickActions.map((item) => <Link key={item.to} to={item.to} className="glass group rounded-[1.5rem] p-5 transition duration-300 hover:-translate-y-1 hover:shadow-card"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary transition group-hover:bg-primary group-hover:text-primary-foreground"><item.icon className="size-5"/></span><h3 className="mt-6 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.detail}</p></Link>)}</div></section>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/15 p-4 backdrop-blur-md" onClick={() => setOpen(false)}><div className="glass-strong w-full max-w-md rounded-[1.5rem] p-6" onClick={e => e.stopPropagation()}><h2 className="text-xl font-semibold">Add pending task</h2><input autoFocus className={`${inputClass} mt-5`} placeholder="Task name" value={name} onChange={e => setName(e.target.value)} onKeyDown={e => e.key === "Enter" && add()}/><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={add}>Add Task</Button></div></div></div>}
  </AppShell>;
}