import { useState } from "react";
import { Mic, Plus, Trash2, UploadCloud } from "lucide-react";
import { AppShell } from "./app-shell";
import { Field, inputClass, PageHeader, SaveBar, Section, textareaClass, ToggleRow } from "./primitives";
import { Button } from "@/components/ui/button";
import { clients, employees } from "@/lib/echo-data";

function Success({ title }: { title: string }) { return <div className="fixed bottom-6 right-6 z-50 rounded-xl bg-success px-5 py-3 text-sm font-semibold text-primary-foreground shadow-card">{title} saved successfully</div>; }
function FormLayout({ title, eyebrow, children, saved, onSubmit }: { title: string; eyebrow: string; children: React.ReactNode; saved: boolean; onSubmit: (e: React.FormEvent) => void }) { return <AppShell><PageHeader title={title} eyebrow={eyebrow}/><form onSubmit={onSubmit} className="grid gap-5">{children}<SaveBar/></form>{saved && <Success title={title}/>}</AppShell>; }
export function NewTaskPage() {
  const [saved, setSaved] = useState(false); const [recording, setRecording] = useState(false); const [reqs, setReqs] = useState<string[]>([]);
  const toggle = (x: string) => setReqs(reqs.includes(x) ? reqs.filter(r => r !== x) : [...reqs, x]);
  return <FormLayout title="Create New Task" eyebrow="Operations" saved={saved} onSubmit={e => { e.preventDefault(); setSaved(true); }}>
    <Section title="Assignment" description="Choose an employee or enter a team member manually."><Field label="Assign to"><select className={inputClass} required><option value="">Select employee</option>{employees.map(e => <option key={e.id}>{e.name}</option>)}</select></Field><Field label="Manual assignee"><input className={inputClass} maxLength={100} placeholder="Type a name"/></Field><Field label="Task description" className="md:col-span-2"><textarea className={textareaClass} required maxLength={1200} placeholder="Describe the expected outcome…"/></Field><div className="md:col-span-2"><Button type="button" variant={recording ? "destructive" : "secondary"} onClick={() => setRecording(!recording)}><Mic className="size-4"/>{recording ? "Stop recording · 00:08" : "Record voice note"}</Button></div></Section>
    <Section title="Schedule"><Field label="Date"><input type="date" className={inputClass} required/></Field><Field label="Check in"><input type="time" className={inputClass} required/></Field><Field label="Check out"><input type="time" className={inputClass} required/></Field></Section>
    <Section title="Employee requirements" description="Selected evidence will appear in the Worker Portal.">{["Upload Before & After", "Upload Voice Reply", "Upload 4 Photos & 1 Video", "Upload Signature", "Upload Mark"].map(x => <ToggleRow key={x} label={x} checked={reqs.includes(x)} onChange={() => toggle(x)}/>)}</Section>
    <Section title="Narrative"><Field label="Additional notes" className="md:col-span-2"><textarea className={textareaClass} maxLength={2000} placeholder="Context, access instructions, or completion notes…"/></Field></Section>
  </FormLayout>;
}
export function NewEmployeePage() {
  const [saved, setSaved] = useState(false); const [account, setAccount] = useState(""); const [confirm, setConfirm] = useState(""); const [tasks, setTasks] = useState([""]); const [permissions, setPermissions] = useState(["Personal Vault"]);
  return <FormLayout title="Create New Employee" eyebrow="People" saved={saved} onSubmit={e => { e.preventDefault(); setSaved(true); }}>
    <Section title="Personal"><Field label="Full name"><input className={inputClass} required maxLength={100}/></Field><Field label="Aadhaar number"><input className={inputClass} inputMode="numeric" pattern="[0-9]{12}" maxLength={12} placeholder="12 digits" required/></Field><Field label="PAN"><input className={inputClass} pattern="[A-Z]{5}[0-9]{4}[A-Z]" maxLength={10} placeholder="ABCDE1234F" required/></Field><Field label="Phone number"><input className={inputClass} inputMode="tel" maxLength={15} required/></Field></Section>
    <Section title="Bank details"><Field label="Account number"><input className={inputClass} value={account} onChange={e => setAccount(e.target.value.replace(/\D/g, "").slice(0, 18))} required/></Field><Field label="Confirm account number"><div className="relative"><input className={inputClass} value={confirm} onChange={e => setConfirm(e.target.value.replace(/\D/g, "").slice(0, 18))} required/><span className={`absolute right-3 top-3 text-xs font-bold ${confirm && confirm === account ? "text-success" : "text-destructive"}`}>{confirm ? confirm === account ? "✓ Match" : "Mismatch" : ""}</span></div></Field><Field label="IFSC"><input className={inputClass} maxLength={11} required/></Field><Field label="Account name"><input className={inputClass} maxLength={100} required/></Field></Section>
    <Section title="Employment"><Field label="Employee code"><input className={inputClass} required/></Field><Field label="Designation"><input className={inputClass} required/></Field><Field label="Monthly salary"><input className={inputClass} type="number" min="0" required/></Field><Field label="Agreement start"><input className={inputClass} type="date" required/></Field><Field label="Agreement end"><input className={inputClass} type="date" required/></Field></Section>
    <Section title="Regular daily tasks" description="Add up to 10 recurring responsibilities."><div className="md:col-span-2 grid gap-3">{tasks.map((task, i) => <div key={i} className="grid gap-2 rounded-xl border border-border p-3 md:grid-cols-[1fr_160px_48px]"><input className={inputClass} placeholder="Task name" value={task} onChange={e => setTasks(tasks.map((t, n) => n === i ? e.target.value : t))}/><select className={inputClass}><option>Daily</option><option>Weekly</option><option>Monthly</option></select><Button type="button" variant="ghost" size="icon" onClick={() => setTasks(tasks.filter((_, n) => n !== i))}><Trash2 className="size-4"/></Button></div>)}<Button type="button" variant="secondary" disabled={tasks.length >= 10} onClick={() => setTasks([...tasks, ""])}><Plus className="size-4"/>Add recurring task</Button></div></Section>
    <Section title="Worker Portal permissions">{["Personal Vault", "Photo Gallery", "Company Official Group", "Voucher Creation"].map(x => <ToggleRow key={x} label={x} checked={permissions.includes(x)} onChange={() => setPermissions(permissions.includes(x) ? permissions.filter(p => p !== x) : [...permissions, x])}/>)}</Section>
  </FormLayout>;
}
export function NewClientPage() { const [saved, setSaved] = useState(false); const [selected, setSelected] = useState<string[]>([employees[0]?.id ?? "", employees[1]?.id ?? ""]); return <FormLayout title="Create New Client" eyebrow="Clients" saved={saved} onSubmit={e => { e.preventDefault(); if (selected.length >= 2) setSaved(true); }}><Section title="Client details"><Field label="Name"><input className={inputClass} required/></Field><Field label="Company"><input className={inputClass} required/></Field><Field label="Phone"><input className={inputClass} inputMode="tel" required/></Field><Field label="Email"><input className={inputClass} type="email" required/></Field><Field label="GSTIN"><input className={inputClass} maxLength={15}/></Field><Field label="GST address"><textarea className={textareaClass}/></Field></Section><Section title="Client group chat" description="Admin and client are added automatically. Choose 2–20 employees.">{employees.map(e => <ToggleRow key={e.id} label={`${e.name} · ${e.role}`} checked={selected.includes(e.id)} onChange={() => setSelected(selected.includes(e.id) ? selected.filter(x => x !== e.id) : [...selected, e.id])}/>) }<p className={`md:col-span-2 text-xs ${selected.length < 2 ? "text-destructive" : "text-muted-foreground"}`}>{selected.length} employees selected · minimum 2, maximum 20</p></Section></FormLayout>; }
export function NewActivityPage() { const [saved, setSaved] = useState(false); return <FormLayout title="Create New Activity" eyebrow="Service desk" saved={saved} onSubmit={e => { e.preventDefault(); setSaved(true); }}><Section title="Complaint details"><Field label="Complaint" className="md:col-span-2"><textarea className={textareaClass} required maxLength={1000}/></Field><Field label="Client name"><select className={inputClass} required><option value="">Select client</option>{clients.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Assigned employee"><select className={inputClass} required><option value="">Select employee</option>{employees.map(e => <option key={e.id}>{e.name}</option>)}</select></Field><Field label="Work required" className="md:col-span-2"><textarea className={textareaClass} required/></Field></Section><Section title="Visual evidence"><UploadBox label="Before photo"/><UploadBox label="After photo"/></Section></FormLayout>; }
function UploadBox({ label }: { label: string }) { return <label className="grid min-h-36 cursor-pointer place-items-center rounded-xl border border-dashed border-input bg-background/40 text-center transition hover:border-primary"><span><UploadCloud className="mx-auto mb-2 size-5 text-primary"/><strong className="text-sm">{label}</strong><small className="mt-1 block text-muted-foreground">Drop a file or browse</small></span><input type="file" accept="image/*" className="hidden"/></label>; }